–ù–∞–∑–≤–∞–Ω–∏–µ: –î–µ–º–æ–Ω—Å—Ç—Ä–∞—Ü–∏—è GitHub Actions
run-name: ${{ github.actor }} —Ç–µ—Å—Ç–∏—Ä—É–µ—Ç GitHub Actions üöÄ
–≤–∫–ª—é—á–µ–Ω–æ: [–Ω–∞–∂–∞—Ç—å]
–≤–∞–∫–∞–Ω—Å–∏–∏:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    —à–∞–≥–∏:
      - run: echo "üéâ –ó–∞–¥–∞–Ω–∏–µ –±—ã–ª–æ –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –∑–∞–ø—É—â–µ–Ω–æ —Å–æ–±—ã—Ç–∏–µ–º ${{ github.event_name }}."
      - run: echo "üêß –≠—Ç–∞ –∑–∞–¥–∞—á–∞ –≤—ã–ø–æ–ª–Ω—è–µ—Ç—Å—è –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ ${{ runner.os }}, —Ä–∞–∑–º–µ—â–µ–Ω–Ω–æ–º –Ω–∞ GitHub!"
      - run: echo "üîé –ù–∞–∑–≤–∞–Ω–∏–µ –≤–∞—à–µ–π –≤–µ—Ç–∫–∏ ‚Äî ${{ github.ref }}, –∞ –≤–∞—à–µ–≥–æ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è ‚Äî ${{ github.repository }}."
      - –∏–º—è: –ü—Ä–æ–≤–µ—Ä–∏—Ç—å –∫–æ–¥ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è
        –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è: actions/checkout@v5
      - run: echo "üí° –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π ${{ github.repository }} –∫–ª–æ–Ω–∏—Ä–æ–≤–∞–Ω –≤ –∏—Å–ø–æ–ª–Ω—è–µ–º—ã–π —Ñ–∞–π–ª."
      - run: echo "üñ•Ô∏è –†–∞–±–æ—á–∏–π –ø—Ä–æ—Ü–µ—Å—Å –≥–æ—Ç–æ–≤ –∫ —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—é –≤–∞—à–µ–≥–æ –∫–æ–¥–∞ –Ω–∞ –∏—Å–ø–æ–ª–Ω–∏—Ç–µ–ª–µ."
      - name: –°–ø–∏—Å–æ–∫ —Ñ–∞–π–ª–æ–≤ –≤ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–∏
        –≤—ã–ø–æ–ª–Ω–∏—Ç—å: |
          ls ${{ github.workspace }}
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üçè –°—Ç–∞—Ç—É—Å —ç—Ç–æ–π –∑–∞–¥–∞—á–∏: ${{ job.status }}."
